permissionBoundary: 'arn:aws:iam::aws:policy/AdministratorAccess'
notebookPath: notebooks
notebookName: rdsconvertor
processingInstanceType: ml.m5.large
securityGroup: <sg-id>
subnetId: <subnet-id>
inputs3bucket: <bucket-name>
input_prefix1: cities
input_prefix2: towns
temp_bucket: <bucket-for-athena-queries-and-notebooks>
