stackName: sage-jupe-101
permissionBoundary: 'arn:aws:iam::aws:policy/AdministratorAccess'
notebookName: rdsconvertor.ipynb
processingInstanceType: ml.m5.large
securityGroup: <sg-id>
subnetId: <subnet-id>
s3bucket: <bucket-name>
input_prefix: input
output_prefix: output
notebook_prefix: notebook
rdsendpoint: <rds-endpoint>
rdsuser: admin
rdspassword: <password>
database: cities
query: 'select * from cities_data'
